# Generated by Django 4.2.3 on 2023-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlistitem_delete_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='is_active',
        ),
    ]
