# Generated by Django 4.2.3 on 2023-07-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlistitem',
            old_name='is_active',
            new_name='is_added',
        ),
    ]
